version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/nutritional_tracker
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - tracker-net
  mongo:
    image: mongo:7.0
    volumes:
      - /volume1/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - tracker-net
networks:
  tracker-net:
    driver: bridge
env_file:
  - .env