export const ENERGY_UNITS = {
    KILOCALORIE: 'kcal',
    KILOJOULE: 'kJ',
};

export const WEIGHT_UNITS = {
    MILLIGRAM: 'mg',
    GRAM: 'g',
    KILOGRAM: 'kg',
    OUNCE: 'oz',
    POUND: 'lb',
};

export const HEIGHT_UNITS = {
    CENTIMETER: 'cm',
    INCH: 'in',
};

export const VOLUME_UNITS = {
    MILLILITER: 'ml',
    FLUID_OUNCE: 'fl_oz',
};

export const UNITS = {
    ENERGY: [ENERGY_UNITS.KILOCALORIE, ENERGY_UNITS.KILOJOULE],
    PRODUCT_WEIGHT: [WEIGHT_UNITS.GRAM, WEIGHT_UNITS.OUNCE],
    PERSON_WEIGHT: [WEIGHT_UNITS.KILOGRAM, WEIGHT_UNITS.POUND],
    VOLUME: [VOLUME_UNITS.MILLILITER, VOLUME_UNITS.FLUID_OUNCE],
    HEIGHT: [HEIGHT_UNITS.CENTIMETER, HEIGHT_UNITS.INCH],
    PACKAGE_SIZE: [WEIGHT_UNITS.GRAM, WEIGHT_UNITS.OUNCE, VOLUME_UNITS.MILLILITER, VOLUME_UNITS.FLUID_OUNCE],
};

export const ENERGY_CONVERSIONS = {
    [ENERGY_UNITS.KILOCALORIE]: {
        [ENERGY_UNITS.KILOJOULE]: 4.184,
    },
    [ENERGY_UNITS.KILOJOULE]: {
        [ENERGY_UNITS.KILOCALORIE]: 0.239006,
    },
};

export const WEIGHT_CONVERSIONS = {
    // Product weight conversions
    [WEIGHT_UNITS.GRAM]: {
        [WEIGHT_UNITS.OUNCE]: 0.03527396,
    },
    [WEIGHT_UNITS.OUNCE]: {
        [WEIGHT_UNITS.GRAM]: 28.3495231,
    },
    // Person weight conversion
    [WEIGHT_UNITS.KILOGRAM]: {
        [WEIGHT_UNITS.POUND]: 2.20462262,
    },
    [WEIGHT_UNITS.POUND]: {
        [WEIGHT_UNITS.KILOGRAM]: 0.45359237,
    },
};

export const HEIGHT_CONVERSIONS = {
    [HEIGHT_UNITS.CENTIMETER]: {
        [HEIGHT_UNITS.INCH]: 0.393700787,
    },
    [HEIGHT_UNITS.INCH]: {
        [HEIGHT_UNITS.CENTIMETER]: 2.54,
    },
};

export const VOLUME_CONVERSIONS = {
    [VOLUME_UNITS.MILLILITER]: {
        [VOLUME_UNITS.FLUID_OUNCE]: 0.033814,
    },
    [VOLUME_UNITS.FLUID_OUNCE]: {
        [VOLUME_UNITS.MILLILITER]: 29.5735,
    },
};
